#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed \
  fzf zoxide ripgrep eza fd stow tmux \
  lazygit lazydocker btop

# Define the folders
export STOW_FOLDERS="bash,nvim,omarchy,omarchy-wsl,starship,tmux"

./stow
