#!/usr/bin/env bash

./run

mkdir ~/.local/share -p
rm ~/.bash_logout ~/.bash_profile ~/.bashrc

stow omarchy/ -t $HOME

# Define the folders
export STOW_FOLDERS="bash,nvim,omarchy,starship,tmux"

../stow
