#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm pkgconf jemalloc
git clone https://github.com/redis/redis --depth 1
cd redis
make redis-cli
sudo cp src/redis-cli /usr/local/bin/

cd ..
rm -rf redis
